### ISSUE TITLE
the beginner examples can not be used?

### ISSUE THREAD

**Issue by huozi07** [LemaireJean-Baptiste/eventstudy#1]
event = es.EventStudy.FamaFrench_3factor(....
AttributeError: module 'eventstudy' has no attribute 'EventStudy'
event I delete es,,, still shows do not have FamaFrench_3factor~~

**Comment by LemaireJean-Baptiste** [comment]
Hello @huozi07, I forgot to update the readme file which was then not describing the current state of the package.

Please refer to the full documentation website which is maintained updated here:
https://lemairejean-baptiste.github.io/eventstudy/
and the get started demo.
https://lemairejean-baptiste.github.io/eventstudy/get_started.html

Currently the interactive version is not working (because of an issue on binder side, but I will try to work on it)

Let me know if you have any issue. I would be pleased to help.
