### ISSUE TITLE
results of event study can't be show in a table

### ISSUE THREAD

**Issue by Richardo-Lu** [LemaireJean-Baptiste/eventstudy#2]
Hi, I am a beginner of python programming and I got a problem on results table. 
I will truly appreciate if  you can help me.
The following is my code:

`event= es.Single.constant_mean(
    security_ticker= 'aapl',
    event_date= np.datetime64('2020-01-16'),
    event_window= (-2,+10),
    estimation_size= 30,
    buffer_size= 0)` 

`event.results(decimals=[3,5,3,5,2,2])`

TypeError                                 Traceback (most recent call last)

<ipython-input-15-9df810868fcd> in <module>
      5     estimation_size= 30,
      6     buffer_size= 0)
----> 7 event.results(decimals=[3,5,3,5,2,2])

D:\Anaconda3\lib\site-packages\eventstudy\single.py in results(self, asterisks, decimals)
    194             asterisks_dict=asterisks_dict,
    195             decimals=decimals,
--> 196             index_start=self.event_window[0],
    197         )
    198 

D:\Anaconda3\lib\site-packages\eventstudy\utils.py in to_table(columns, asterisks_dict, decimals, index_start)
     28         )
     29 
---> 30     df = pd.DataFrame.from_dict(columns)
     31     df.index += index_start
     32     return df

D:\Anaconda3\lib\site-packages\pandas\core\frame.py in from_dict(cls, data, orient, dtype, columns)
   1136             raise ValueError('only recognize index or columns for orient')
   1137 
-> 1138         return cls(data, index=index, columns=columns, dtype=dtype)
   1139 
   1140     def to_numpy(self, dtype=None, copy=False):

D:\Anaconda3\lib\site-packages\pandas\core\frame.py in __init__(self, data, index, columns, dtype, copy)
    390                                  dtype=dtype, copy=copy)
    391         elif isinstance(data, dict):
--> 392             mgr = init_dict(data, index, columns, dtype=dtype)
    393         elif isinstance(data, ma.MaskedArray):
    394             import numpy.ma.mrecords as mrecords

D:\Anaconda3\lib\site-packages\pandas\core\internals\construction.py in init_dict(data, index, columns, dtype)
    210         arrays = [data[k] for k in keys]
    211 
--> 212     return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
    213 
    214 

D:\Anaconda3\lib\site-packages\pandas\core\internals\construction.py in arrays_to_mgr(arrays, arr_names, index, columns, dtype)
     49     # figure out the index, if necessary
     50     if index is None:
---> 51         index = extract_index(arrays)
     52     else:
     53         index = ensure_index(index)

D:\Anaconda3\lib\site-packages\pandas\core\internals\construction.py in extract_index(data)
    303             elif is_list_like(val) and getattr(val, 'ndim', 1) == 1:
    304                 have_raw_arrays = True
--> 305                 raw_lengths.append(len(val))
    306 
    307         if not indexes and not raw_lengths:

TypeError: object of type 'map' has no len()

**Comment by chestnut-ai** [comment]
hi，from my experience to use this package you need to import data in a specific format ,otherwise all kinds of errors are going to pop out .Sorry I am also not a specialist in python ,but I have attached to this email a copy of the data file I used when conducting this program successfully ,you could check its format, and hopefully it will be useful :)




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Richardo-Lu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月17日(星期三) 上午6:37
收件人:&nbsp;"LemaireJean-Baptiste/eventstudy"<eventstudy@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[LemaireJean-Baptiste/eventstudy] results of event study can't be show in a table (#2)





 
Hi, I am a beginner of python programming and I got a problem on results table.
 I will truly appreciate if  you can help me.
 The following is my code:
 
event= es.Single.constant_mean( security_ticker= 'aapl', event_date= np.datetime64('2020-01-16'), event_window= (-2,+10), estimation_size= 30, buffer_size= 0)
 
event.results(decimals=[3,5,3,5,2,2])
 
TypeError                                 Traceback (most recent call last)
 
 in 
 5     estimation_size= 30,
 6     buffer_size= 0)
 ----&gt; 7 event.results(decimals=[3,5,3,5,2,2])
 
D:\Anaconda3\lib\site-packages\eventstudy\single.py in results(self, asterisks, decimals)
 194             asterisks_dict=asterisks_dict,
 195             decimals=decimals,
 --&gt; 196             index_start=self.event_window[0],
 197         )
 198
 
D:\Anaconda3\lib\site-packages\eventstudy\utils.py in to_table(columns, asterisks_dict, decimals, index_start)
 28         )
 29
 ---&gt; 30     df = pd.DataFrame.from_dict(columns)
 31     df.index += index_start
 32     return df
 
D:\Anaconda3\lib\site-packages\pandas\core\frame.py in from_dict(cls, data, orient, dtype, columns)
 1136             raise ValueError('only recognize index or columns for orient')
 1137
 -&gt; 1138         return cls(data, index=index, columns=columns, dtype=dtype)
 1139
 1140     def to_numpy(self, dtype=None, copy=False):
 
D:\Anaconda3\lib\site-packages\pandas\core\frame.py in init(self, data, index, columns, dtype, copy)
 390                                  dtype=dtype, copy=copy)
 391         elif isinstance(data, dict):
 --&gt; 392             mgr = init_dict(data, index, columns, dtype=dtype)
 393         elif isinstance(data, ma.MaskedArray):
 394             import numpy.ma.mrecords as mrecords
 
D:\Anaconda3\lib\site-packages\pandas\core\internals\construction.py in init_dict(data, index, columns, dtype)
 210         arrays = [data[k] for k in keys]
 211
 --&gt; 212     return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
 213
 214
 
D:\Anaconda3\lib\site-packages\pandas\core\internals\construction.py in arrays_to_mgr(arrays, arr_names, index, columns, dtype)
 49     # figure out the index, if necessary
 50     if index is None:
 ---&gt; 51         index = extract_index(arrays)
 52     else:
 53         index = ensure_index(index)
 
D:\Anaconda3\lib\site-packages\pandas\core\internals\construction.py in extract_index(data)
 303             elif is_list_like(val) and getattr(val, 'ndim', 1) == 1:
 304                 have_raw_arrays = True
 --&gt; 305                 raw_lengths.append(len(val))
 306
 307         if not indexes and not raw_lengths:
 
TypeError: object of type 'map' has no len()

**Comment by LemaireJean-Baptiste** [comment]
Hello @Richardo-Lu and @chestnut-ai, thanks for your messages. This package is still in beta, and the error-handling part is not complete. As said by @chestnut-ai, the dataframe imported (using csv through the [import data functions](https://lemairejean-baptiste.github.io/eventstudy/api/eventstudy.Single.html#import-data)) must followed a standard format.
You can find an example for this format here: [EventStudy/example](https://github.com/LemaireJean-Baptiste/eventstudy/tree/master/example) (check 10K.csv and famafrench.csv).

These data importing functions may be rewritten to solve some issues you can face where some periods are missing. I will have to find some time for that (obviously contributors are welcome).

**Comment by Richardo-Lu** [comment]
> 
> hi，from my experience to use this package you need to import data in a specific format ,otherwise all kinds of errors are going to pop out .Sorry I am also not a specialist in python ,but I have attached to this email a copy of the data file I used when conducting this program successfully ,you could check its format, and hopefully it will be useful :)
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Richardo-Lu"<notifications@github.com&gt;; 发送时间:&nbsp;2020年6月17日(星期三) 上午6:37 收件人:&nbsp;"LemaireJean-Baptiste/eventstudy"<eventstudy@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[LemaireJean-Baptiste/eventstudy] results of event study can't be show in a table (#2) Hi, I am a beginner of python programming and I got a problem on results table. I will truly appreciate if you can help me. The following is my code: event= es.Single.constant_mean( security_ticker= 'aapl', event_date= np.datetime64('2020-01-16'), event_window= (-2,+10), estimation_size= 30, buffer_size= 0) event.results(decimals=[3,5,3,5,2,2]) TypeError Traceback (most recent call last) in 5 estimation_size= 30, 6 buffer_size= 0) ----&gt; 7 event.results(decimals=[3,5,3,5,2,2]) D:\Anaconda3\lib\site-packages\eventstudy\single.py in results(self, asterisks, decimals) 194 asterisks_dict=asterisks_dict, 195 decimals=decimals, --&gt; 196 index_start=self.event_window[0], 197 ) 198 D:\Anaconda3\lib\site-packages\eventstudy\utils.py in to_table(columns, asterisks_dict, decimals, index_start) 28 ) 29 ---&gt; 30 df = pd.DataFrame.from_dict(columns) 31 df.index += index_start 32 return df D:\Anaconda3\lib\site-packages\pandas\core\frame.py in from_dict(cls, data, orient, dtype, columns) 1136 raise ValueError('only recognize index or columns for orient') 1137 -&gt; 1138 return cls(data, index=index, columns=columns, dtype=dtype) 1139 1140 def to_numpy(self, dtype=None, copy=False): D:\Anaconda3\lib\site-packages\pandas\core\frame.py in init(self, data, index, columns, dtype, copy) 390 dtype=dtype, copy=copy) 391 elif isinstance(data, dict): --&gt; 392 mgr = init_dict(data, index, columns, dtype=dtype) 393 elif isinstance(data, ma.MaskedArray): 394 import numpy.ma.mrecords as mrecords D:\Anaconda3\lib\site-packages\pandas\core\internals\construction.py in init_dict(data, index, columns, dtype) 210 arrays = [data[k] for k in keys] 211 --&gt; 212 return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype) 213 214 D:\Anaconda3\lib\site-packages\pandas\core\internals\construction.py in arrays_to_mgr(arrays, arr_names, index, columns, dtype) 49 # figure out the index, if necessary 50 if index is None: ---&gt; 51 index = extract_index(arrays) 52 else: 53 index = ensure_index(index) D:\Anaconda3\lib\site-packages\pandas\core\internals\construction.py in extract_index(data) 303 elif is_list_like(val) and getattr(val, 'ndim', 1) == 1: 304 have_raw_arrays = True --&gt; 305 raw_lengths.append(len(val)) 306 307 if not indexes and not raw_lengths: TypeError: object of type 'map' has no len() — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Richardo-Lu** [comment]
Hi @chestnut-ai  
Sorry that I don't find your attached, and I am not sure where I can find it.
Can you help me and send it again? Thanks a lot!

**Comment by Richardo-Lu** [comment]
I am not sure whether the dataset is in a standard format, because the result can be plotted.
![图片](https://user-images.githubusercontent.com/67028148/84901775-3b102a00-b0ac-11ea-8242-de3c7cab76c2.png)

**Comment by chestnut-ai** [comment]
&nbsp;I don't know why you didn't get my attachment ... I have attached it to this email , hope you can get it this time .In case you don't I have taken this screenshot , this is the standard format (ps.be aware that in the first column the word"date" has to to be in small capitals.)
Good luck !





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Richardo-Lu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月17日(星期三) 晚上9:11
收件人:&nbsp;"LemaireJean-Baptiste/eventstudy"<eventstudy@noreply.github.com&gt;;
抄送:&nbsp;"刘佳音"<1127540416@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [LemaireJean-Baptiste/eventstudy] results of event study can't be show in a table (#2)





 
I am not sure whether the dataset is in a standard format, because the result can be plotted.

**Comment by Richardo-Lu** [comment]
Can you show me how to check your attachment? I am a beginner of GitHub.
And can you see my screenshot here?
![图片](https://user-images.githubusercontent.com/67028148/84905712-4f0a5a80-b0b1-11ea-84b6-46b11428648f.png)

**Comment by Richardo-Lu** [comment]
By the way, can you send it to my email  ludongr1993@sina.com ?

**Comment by Richardo-Lu** [comment]
Hi @LemaireJean-Baptiste  Would you mind updating this package or fix the error as soon as possible? Since it's really important for my thesis, I hope to use it eagerly! Thanks a lot!
I have downloaded 'returns_GAFAM.csv' and 'famafrench.csv' from example folder and run your example code [https://github.com/LemaireJean-Baptiste/eventstudy/blob/master/example/Eventstudy%20Example.ipynb](url). I still can't get results table. The error information looks same as what I got yesterday. You can see on my screenshots. 
![图片](https://user-images.githubusercontent.com/67028148/84917056-212c1280-b0bf-11ea-9c4c-d857120c6cf4.png)
![图片](https://user-images.githubusercontent.com/67028148/84917144-3dc84a80-b0bf-11ea-9fe9-c900f1ce2335.png)
![图片](https://user-images.githubusercontent.com/67028148/84917217-533d7480-b0bf-11ea-9c8a-15362f960603.png)

**Comment by chestnut-ai** [comment]
hi, if you want to conduct this program on a set of events or multiple companies you can find the codes in the GitHub page of this package ! Just check &nbsp;EventStudy/example&nbsp;. This package's only problem is that it will produce some missing data when running , but that's not a big issue , my team has been written a thesis which also depends on this package , and we found this package really helpful!
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"LemaireJean-Baptiste"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月17日(星期三) 下午4:52
收件人:&nbsp;"LemaireJean-Baptiste/eventstudy"<eventstudy@noreply.github.com&gt;;
抄送:&nbsp;"刘佳音"<1127540416@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [LemaireJean-Baptiste/eventstudy] results of event study can't be show in a table (#2)





 
Hello @Richardo-Lu and @chestnut-ai, thanks for your messages. This package is still in beta, and the error-handling part is not complete. As said by @chestnut-ai, the dataframe imported (using csv through the import data functions) must followed a standard format.
 You can find an example for this format here: EventStudy/example (check 10K.csv and famafrench.csv).
 
These data importing functions may be rewritten to solve some issues you can face where some periods are missing. I will have to find some time for that (obviously contributors are welcome).

**Comment by creigber** [comment]
Dear @LemaireJean-Baptiste,

I am also trying to work with your python package as it seems to be the best one available for event studies with multiple firms and multiple events per firm. I am very thankful for you having programmed this package. I am also having trouble having the results shown in a table. When I use the .results function the CAAR column always shows "<map object at 0x7fb439e6c240>". I think this has something to do with the way that you have to recast the map object with list(), but I don't know how to fix this. Maybe you can help me somehow.

Best regards, 

Constantin

**Comment by LemaireJean-Baptiste** [comment]
Hello All,
This project was on standby, I will have time next week to investigate your bugs.
I will rewrite a substantial part of the code to get rid of these issues. It is coming from some data issue, I will add a stronger data validation process and reorganise the way I store time-series. I will also better document import functions.

Can you send me your code and data (in a zip file) on my email address:
lemaire.jeanbaptiste@gmail.com

If you have some comments or improvements ideas, you can send it in a new issue. I will devote some weeks this summer to release a stable version of the tool (all contributors are welcome).

Best regards,
JB
